### ISSUE TITLE
What to do for frame sequential Quad buffer stereo

### ISSUE THREAD

**Issue by RYG81** [livingenvironmentslab/UniCAVE#1]
Hi,
 I m trying to use your plugin on a demo scene Unity Lab. I want to achieve Quadro card bases Quadd buffer stereo effect that can be sued on DLP linked 3D projector. Please help me on steps to do this.
Rahul

**Comment by livingenvironmentslab** [comment]
Hi Rahul,

There are a couple of different ways to do this with the plugin depending on which version of Unity, etc.  You should be able to check the "Virtual Reality Supported" checkbox and then choose "Stereo Display (non-head mounted)".  Assuming you have the correct nVidia settings in your control panel setup, etc. this should work.  If trying with a version of Unity prior to 5.2 or if trying the above technique doesn't work e-mail me at rdtredinnick@wisc.edu and I can help further through e-mail.

Ross
