### ISSUE TITLE
2017.3 Net broken

### ISSUE THREAD

**Issue by fingerx** [livingenvironmentslab/UniCAVE#4]
network view deprecated, can you update old net to unet? thanks very much.

**Comment by jamesmoney** [comment]
@rossTnick Looked at this a while back and it seemed like it would be straightforward. Thoughts?

**Comment by fingerx** [comment]
@jamesmoney  Can you add sync frame lock? thanks for share unicave,this is great project.

**Comment by jamesmoney** [comment]
Sync frame lock should be coming from your Nvidia sync card. We do not have any systems that use software based frame lock.

**Comment by jamesmoney** [comment]
Also, it appears only the one prefab for a tiled display uses network view, so you can probably delete the files in 2018, which is what we have done.

**Comment by fingerx** [comment]
@jamesmoney thanks.Hardware frame synchronization is very expensive. If  use unicave and hardware frame synchronization, does unicave need special settings?Is there any setup information about hardware frame synchronization? Unity Including Cluster Rendering（softeware frame lock ）but is beta.Is Unicave considering adding software frame synchronization? Thanks again.

**Comment by rossTnick** [comment]
Hi Yan,

I don’t believe you would need any special settings if your hardware frame synchronization is active.  As far as Unity 2018 support - we will aim to have it out either later this month or next month.  We have a working version in our lab, but need to test out a few additional stereo setups, etc.

We haven’t considered adding software frame sync, the networking send rate could be increased to potentially help if you are experiencing frame sync issues.

Ross

**Comment by fingerx** [comment]
@rossTnick thanks very much.
